baseURL: https://maakun12.github.io
languageCode: ja
theme: hugo-coder
title: maakun12
copyright: © maakun12
params:
  author: maakun12
  info: I'm a Web Developer
  avatarURL: images/logo.png
  colorScheme: "dark"
  social:
    - name: Github
      icon: fa fa-2x fa-github
      weight: 1
      url: https://github.com/maakun12/
  hideColorSchemeToggle: false
menus:
  main:
    - name: Blog
      url: /posts/
